from setuptools import setup, find_packages

setup(
    name="vbot",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.26.0,<2.0.0",
        "scipy==1.14.1",
        "pandas==2.2.3",
        "torch>=2.5.1",
        "wxPython==4.2.2",
        "numpy>=1.26.0,<2.0.0",
        "scipy==1.14.1",
        "pandas==2.2.3",
        "accelerate==1.1.1",
        "tensorboard==2.18.0",
        "huggingface-hub==0.26.2",
        "transformers==4.46.3",
        "bitsandbytes==0.44.1",
        "soundfile==0.12.1",
        "librosa==0.10.2.post1",
        "sounddevice==0.5.1",
        "pyaudio==0.2.14",
        "speechbrain==1.0.2",
        "faster-whisper==1.0.3",
        "phonemizer==3.3.0",
        "nltk==3.9.1",
        "munch==4.0.0",
        "num2words==0.5.13",
        "requests==2.32.3",
        "pillow==11.0.0",
        "resemblyzer==0.1.4",
        "tqdm==4.67.0",
        "pesq==0.0.4",
        "bert_score==0.3.13",
        "rouge_score==0.1.2",
        "evaluate==0.4.3",
        "docker==7.1.0",
        "pystoi==0.4.1",
        "mir_eval==0.7",
        "pysrt",
        "git+https://github.com/m-bain/whisperx.git",
        "wxPython==4.2.2",
    ],
    entry_points={
        'console_scripts': [
            'run-animation=tha4.app.autonomous_animation:main',
        ],
    },
    author="Your Name",
    description="VBot Animation System",
    python_requires=">=3.10",
) 